// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcureHub.SharedKernel.Database;

#nullable disable

namespace ProcureHub.SharedKernel.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626041415_MasterDataSchema")]
    partial class MasterDataSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("created_by_id");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("DECIMAL(18,6)")
                        .HasColumnName("exchange_rate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBase")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_base");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_currencies_code");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_currencies_created_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_currencies_updated_by_id");

                    b.ToTable("currencies", (string)null);
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Indonesia")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("province");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_locations_created_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_locations_updated_by_id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("created_by_id");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("currency_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<decimal?>("EstimatedPrice")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("estimated_price");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsStrategic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_strategic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("UomId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("uom_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_materials_category_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_materials_code");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_materials_created_by_id");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_materials_currency_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_materials_deleted_by_id");

                    b.HasIndex("UomId")
                        .HasDatabaseName("ix_materials_uom_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_materials_updated_by_id");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.MaterialCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsStrategic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_strategic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("parent_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_material_categories");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_material_categories_created_by_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_material_categories_parent_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_material_categories_updated_by_id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_material_categories_company_id_code");

                    b.ToTable("material_categories", (string)null);
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.PaymentTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("created_by_id");

                    b.Property<int>("Days")
                        .HasColumnType("int")
                        .HasColumnName("days");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_terms");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_payment_terms_created_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_payment_terms_updated_by_id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_terms_company_id_code");

                    b.ToTable("payment_terms", (string)null);
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_unit_of_measures");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_unit_of_measures_created_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_unit_of_measures_updated_by_id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_of_measures_company_id_code");

                    b.ToTable("unit_of_measures", (string)null);
                });

            modelBuilder.Entity("ProcureHub.SharedKernel.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("action");

                    b.Property<string>("AfterValues")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("after_values");

                    b.Property<string>("BeforeValues")
                        .HasColumnType("TEXT")
                        .HasColumnName("before_values");

                    b.Property<string>("ChangedColumns")
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_columns");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("user_full_name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_audit_logs_entity_type");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ProcureHub.SharedKernel.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_code");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_companies_created_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_companies_updated_by_id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("ProcureHub.SharedKernel.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("created_by_id");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("keycloak_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_users_company_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_users_created_by_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("KeycloakId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_keycloak_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_users_updated_by_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.Currency", b =>
                {
                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_currencies_users_created_by_id");

                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_currencies_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.Location", b =>
                {
                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_locations_users_created_by_id");

                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_locations_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.Material", b =>
                {
                    b.HasOne("ProcureHub.Modules.MasterData.Domain.Entities.MaterialCategory", "Category")
                        .WithMany("Materials")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_materials_material_categories_category_id");

                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_materials_users_created_by_id");

                    b.HasOne("ProcureHub.Modules.MasterData.Domain.Entities.Currency", "Currency")
                        .WithMany("Materials")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_materials_currencies_currency_id");

                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_materials_users_deleted_by_id");

                    b.HasOne("ProcureHub.Modules.MasterData.Domain.Entities.UnitOfMeasure", "Uom")
                        .WithMany("Materials")
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_materials_unit_of_measure_uom_id");

                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_materials_users_updated_by_id");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("Currency");

                    b.Navigation("DeletedBy");

                    b.Navigation("Uom");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.MaterialCategory", b =>
                {
                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_material_categories_users_created_by_id");

                    b.HasOne("ProcureHub.Modules.MasterData.Domain.Entities.MaterialCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_material_categories_material_categories_parent_id");

                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_material_categories_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Parent");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.PaymentTerm", b =>
                {
                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payment_terms_users_created_by_id");

                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payment_terms_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_unit_of_measures_users_created_by_id");

                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_unit_of_measures_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ProcureHub.SharedKernel.Domain.Company", b =>
                {
                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_companies_users_created_by_id");

                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_companies_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ProcureHub.SharedKernel.Domain.User", b =>
                {
                    b.HasOne("ProcureHub.SharedKernel.Domain.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_companies_company_id");

                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_created_by_id");

                    b.HasOne("ProcureHub.SharedKernel.Domain.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_updated_by_id");

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.Currency", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.MaterialCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("ProcureHub.Modules.MasterData.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
